/* Generated By:JJTree: Do not edit this line. ASTFnInvoke.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=interpreter.BaseASTNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTFnInvoke extends SimpleNode {
  public ASTFnInvoke(int id) {
    super(id);
  }

  public ASTFnInvoke(Rattle p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RattleVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=3caed962b70528d2cc1d557f3578670c (do not edit this line) */
