/* Generated By:JJTree: Do not edit this line. ASTFileLoad.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=interpreter.BaseASTNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTFileLoad extends SimpleNode {
  public ASTFileLoad(int id) {
    super(id);
  }

  public ASTFileLoad(Rattle p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RattleVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=d1fd4aa04f4ed9c08edec661fb0753ff (do not edit this line) */
