/* Generated By:JJTree: Do not edit this line. ASTIndexedExpression.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=interpreter.BaseASTNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTIndexedExpression extends SimpleNode {
  public ASTIndexedExpression(int id) {
    super(id);
  }

  public ASTIndexedExpression(Rattle p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RattleVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=05250d0d13019ac0a4ae6269f679eb12 (do not edit this line) */
