/* Generated By:JJTree: Do not edit this line. ASTLabmdaDefine.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=interpreter.BaseASTNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTLabmdaDefine extends SimpleNode {
  public ASTLabmdaDefine(int id) {
    super(id);
  }

  public ASTLabmdaDefine(Rattle p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RattleVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=a979cc1954a13a91f4404ed032423a09 (do not edit this line) */
