/* Generated By:JJTree: Do not edit this line. ASTMethodInstantiate.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=interpreter.BaseASTNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTMethodInstantiate extends SimpleNode {
  public ASTMethodInstantiate(int id) {
    super(id);
  }

  public ASTMethodInstantiate(Rattle p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RattleVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=3f1c4c0dd3b52632da887a35d28f82bd (do not edit this line) */
