/* Generated By:JJTree: Do not edit this line. ASTMultiAssignment.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=interpreter.BaseASTNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTMultiAssignment extends SimpleNode {
  public ASTMultiAssignment(int id) {
    super(id);
  }

  public ASTMultiAssignment(Rattle p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RattleVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=0b3b02834309b6882996dcc69bd0949b (do not edit this line) */
