/* Generated By:JJTree: Do not edit this line. ASTMemInstantiate.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=interpreter.BaseASTNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTMemInstantiate extends SimpleNode {
  public ASTMemInstantiate(int id) {
    super(id);
  }

  public ASTMemInstantiate(Rattle p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RattleVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=3304b9331dc7568667f0113941591cdb (do not edit this line) */
