/* Generated By:JavaCC: Do not edit this line. RattleVisitor.java Version 6.0_1 */
package parser;

public interface RattleVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTCode node, Object data);
  public Object visit(ASTStatement node, Object data);
  public Object visit(ASTBlock node, Object data);
  public Object visit(ASTParmlist node, Object data);
  public Object visit(ASTClassDef node, Object data);
  public Object visit(ASTFnBody node, Object data);
  public Object visit(ASTFnDef node, Object data);
  public Object visit(ASTReturnExpression node, Object data);
  public Object visit(ASTMemAssignment node, Object data);
  public Object visit(ASTAssignment node, Object data);
  public Object visit(ASTIfStatement node, Object data);
  public Object visit(ASTObjCreate node, Object data);
  public Object visit(ASTMemInstantiate node, Object data);
  public Object visit(ASTMethodInstantiate node, Object data);
  public Object visit(ASTLabmdaDefine node, Object data);
  public Object visit(ASTForLoop node, Object data);
  public Object visit(ASTWhileLoop node, Object data);
  public Object visit(ASTWrite node, Object data);
  public Object visit(ASTArgList node, Object data);
  public Object visit(ASTOr node, Object data);
  public Object visit(ASTAnd node, Object data);
  public Object visit(ASTCompEqual node, Object data);
  public Object visit(ASTCompNequal node, Object data);
  public Object visit(ASTCompGTE node, Object data);
  public Object visit(ASTCompLTE node, Object data);
  public Object visit(ASTCompGT node, Object data);
  public Object visit(ASTCompLT node, Object data);
  public Object visit(ASTAdd node, Object data);
  public Object visit(ASTSubtract node, Object data);
  public Object visit(ASTTimes node, Object data);
  public Object visit(ASTDivide node, Object data);
  public Object visit(ASTUnaryNot node, Object data);
  public Object visit(ASTUnaryPlus node, Object data);
  public Object visit(ASTUnaryMinus node, Object data);
  public Object visit(ASTFnInvoke node, Object data);
  public Object visit(ASTMethodInvoke node, Object data);
  public Object visit(ASTIdentifier node, Object data);
  public Object visit(ASTMemIdentifier node, Object data);
  public Object visit(ASTDereference node, Object data);
  public Object visit(ASTCharacter node, Object data);
  public Object visit(ASTNumber node, Object data);
  public Object visit(ASTTrue node, Object data);
  public Object visit(ASTFalse node, Object data);
}
/* JavaCC - OriginalChecksum=399b11ce6309f368e56c3adcdb8b758d (do not edit this line) */
