/* Generated By:JavaCC: Do not edit this line. RattleDefaultVisitor.java Version 7.0.0 */
package parser;

public class RattleDefaultVisitor implements RattleVisitor{
  public Object defaultVisit(SimpleNode node, Object data){
    node.childrenAccept(this, data);
    return data;
  }
  public Object visit(SimpleNode node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTCode node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTStatement node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTBlock node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTParmlist node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTClassDef node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTFnBody node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTFnDef node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTReturnExpression node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTMemAssignment node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTTupleDefine node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTAssignment node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTMultiAssignment node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTIfStatement node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTObjCreate node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTMemInstantiate node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTMethodInstantiate node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTLabmdaDefine node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTForLoop node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTWhileLoop node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTWrite node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTArgList node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTOr node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTAnd node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTCompEqual node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTCompNequal node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTCompGTE node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTCompLTE node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTCompGT node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTCompLT node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTAdd node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTSubtract node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTTimes node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTDivide node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTUnaryNot node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTUnaryPlus node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTUnaryMinus node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTIndexedExpression node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTFnInvoke node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTMethodInvoke node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTIdentifier node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTMemIdentifier node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTDereference node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTCharacter node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTInteger node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTRational node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTTrue node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTFalse node, Object data){
    return defaultVisit(node, data);
  }
}
/* JavaCC - OriginalChecksum=947372b5b73f8e3bf749cab4fae7bbd6 (do not edit this line) */
