/* Generated By:JavaCC: Do not edit this line. RattleTreeConstants.java Version 7.0.0 */
package parser;

public interface RattleTreeConstants
{
  public int JJTCODE = 0;
  public int JJTSTATEMENT = 1;
  public int JJTBLOCK = 2;
  public int JJTPARMLIST = 3;
  public int JJTCLASSDEF = 4;
  public int JJTFNBODY = 5;
  public int JJTNULL = 6;
  public int JJTFNDEF = 7;
  public int JJTRETURNEXPRESSION = 8;
  public int JJTMEMASSIGNMENT = 9;
  public int JJTFILELOAD = 10;
  public int JJTTUPLEDEFINE = 11;
  public int JJTASSIGNMENT = 12;
  public int JJTMULTIASSIGNMENT = 13;
  public int JJTIFSTATEMENT = 14;
  public int JJTOBJCREATE = 15;
  public int JJTMEMINSTANTIATE = 16;
  public int JJTMETHODINSTANTIATE = 17;
  public int JJTLABMDADEFINE = 18;
  public int JJTFORLOOP = 19;
  public int JJTWHILELOOP = 20;
  public int JJTWRITE = 21;
  public int JJTARGLIST = 22;
  public int JJTVOID = 23;
  public int JJTOR = 24;
  public int JJTAND = 25;
  public int JJTCOMPEQUAL = 26;
  public int JJTCOMPNEQUAL = 27;
  public int JJTCOMPGTE = 28;
  public int JJTCOMPLTE = 29;
  public int JJTCOMPGT = 30;
  public int JJTCOMPLT = 31;
  public int JJTADD = 32;
  public int JJTSUBTRACT = 33;
  public int JJTTIMES = 34;
  public int JJTDIVIDE = 35;
  public int JJTUNARYNOT = 36;
  public int JJTUNARYPLUS = 37;
  public int JJTUNARYMINUS = 38;
  public int JJTINDEXEDEXPRESSION = 39;
  public int JJTFNINVOKE = 40;
  public int JJTMETHODINVOKE = 41;
  public int JJTIDENTIFIER = 42;
  public int JJTMEMIDENTIFIER = 43;
  public int JJTDEREFERENCE = 44;
  public int JJTCHARACTER = 45;
  public int JJTINTEGER = 46;
  public int JJTRATIONAL = 47;
  public int JJTTRUE = 48;
  public int JJTFALSE = 49;


  public String[] jjtNodeName = {
    "Code",
    "Statement",
    "Block",
    "Parmlist",
    "ClassDef",
    "FnBody",
    "NULL",
    "FnDef",
    "ReturnExpression",
    "MemAssignment",
    "FileLoad",
    "TupleDefine",
    "Assignment",
    "MultiAssignment",
    "IfStatement",
    "ObjCreate",
    "MemInstantiate",
    "MethodInstantiate",
    "LabmdaDefine",
    "ForLoop",
    "WhileLoop",
    "Write",
    "ArgList",
    "void",
    "Or",
    "And",
    "CompEqual",
    "CompNequal",
    "CompGTE",
    "CompLTE",
    "CompGT",
    "CompLT",
    "Add",
    "Subtract",
    "Times",
    "Divide",
    "UnaryNot",
    "UnaryPlus",
    "UnaryMinus",
    "IndexedExpression",
    "FnInvoke",
    "MethodInvoke",
    "Identifier",
    "MemIdentifier",
    "Dereference",
    "Character",
    "Integer",
    "Rational",
    "True",
    "False",
  };
}
/* JavaCC - OriginalChecksum=3948b523bc7d2beb4197a4a270f5dcfd (do not edit this line) */
