/* Generated By:JavaCC: Do not edit this line. RattleTreeConstants.java Version 7.0.0 */
package parser;

public interface RattleTreeConstants
{
  public int JJTCODE = 0;
  public int JJTSTATEMENT = 1;
  public int JJTBLOCK = 2;
  public int JJTPARMLIST = 3;
  public int JJTCLASSDEF = 4;
  public int JJTFNBODY = 5;
  public int JJTNULL = 6;
  public int JJTFNDEF = 7;
  public int JJTRETURNEXPRESSION = 8;
  public int JJTMEMASSIGNMENT = 9;
  public int JJTNETLOAD = 10;
  public int JJTFILELOAD = 11;
  public int JJTTUPLEDEFINE = 12;
  public int JJTASSIGNMENT = 13;
  public int JJTMULTIASSIGNMENT = 14;
  public int JJTIFSTATEMENT = 15;
  public int JJTOBJCREATE = 16;
  public int JJTMEMINSTANTIATE = 17;
  public int JJTMETHODINSTANTIATE = 18;
  public int JJTLABMDADEFINE = 19;
  public int JJTFORLOOP = 20;
  public int JJTWHILELOOP = 21;
  public int JJTWRITE = 22;
  public int JJTARGLIST = 23;
  public int JJTVOID = 24;
  public int JJTOR = 25;
  public int JJTAND = 26;
  public int JJTCOMPEQUAL = 27;
  public int JJTCOMPNEQUAL = 28;
  public int JJTCOMPGTE = 29;
  public int JJTCOMPLTE = 30;
  public int JJTCOMPGT = 31;
  public int JJTCOMPLT = 32;
  public int JJTADD = 33;
  public int JJTSUBTRACT = 34;
  public int JJTTIMES = 35;
  public int JJTDIVIDE = 36;
  public int JJTUNARYNOT = 37;
  public int JJTUNARYPLUS = 38;
  public int JJTUNARYMINUS = 39;
  public int JJTINDEXEDEXPRESSION = 40;
  public int JJTFNINVOKE = 41;
  public int JJTMETHODINVOKE = 42;
  public int JJTIDENTIFIER = 43;
  public int JJTMEMIDENTIFIER = 44;
  public int JJTDEREFERENCE = 45;
  public int JJTCHARACTER = 46;
  public int JJTINTEGER = 47;
  public int JJTRATIONAL = 48;
  public int JJTTRUE = 49;
  public int JJTFALSE = 50;


  public String[] jjtNodeName = {
    "Code",
    "Statement",
    "Block",
    "Parmlist",
    "ClassDef",
    "FnBody",
    "NULL",
    "FnDef",
    "ReturnExpression",
    "MemAssignment",
    "NetLoad",
    "FileLoad",
    "TupleDefine",
    "Assignment",
    "MultiAssignment",
    "IfStatement",
    "ObjCreate",
    "MemInstantiate",
    "MethodInstantiate",
    "LabmdaDefine",
    "ForLoop",
    "WhileLoop",
    "Write",
    "ArgList",
    "void",
    "Or",
    "And",
    "CompEqual",
    "CompNequal",
    "CompGTE",
    "CompLTE",
    "CompGT",
    "CompLT",
    "Add",
    "Subtract",
    "Times",
    "Divide",
    "UnaryNot",
    "UnaryPlus",
    "UnaryMinus",
    "IndexedExpression",
    "FnInvoke",
    "MethodInvoke",
    "Identifier",
    "MemIdentifier",
    "Dereference",
    "Character",
    "Integer",
    "Rational",
    "True",
    "False",
  };
}
/* JavaCC - OriginalChecksum=8e277714e11f31f3ff445d21cbbec3c9 (do not edit this line) */
